#Kiosk
- platform: mqtt
  name: dashboard_motion
  state_topic: note3/kiosk
  device_class: motion

- platform: mqtt
  state_topic: "mailbox-flag/reading"
  name: Mailbox Flag
  device_class: light

- platform: mqtt
  state_topic: "mailbox-green/reading"
  name: Mailbox Green Light
  device_class: light

- platform: mqtt
  state_topic: "mailbox-red/reading"
  name: Mailbox Red Light
  device_class: light

- platform: huesensor