homeassistant:
  name: !secret config_name
  latitude: !secret config_lat
  longitude: !secret config_long
  elevation: !secret config_elev
  unit_system: imperial
  time_zone: !secret config_tz
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  whitelist_external_dirs:
      - /home/homeassistant/.homeassistant/scripts
      - /home/homeassistant/.homeassistant/www/images/
      - /home/homeassistant/.homeassistant/downloads/

# Enables the frontend
frontend: 
  javascript_version: latest
#  themes: !include configuration_themes.yaml
#  extra_html_url:
#    - /local/custom_ui/custom-weather-card.html
#    - /local/custom_ui/state-card-floorplan.html
#    - /local/custom_ui/state-card-tiles.html
#    - /local/custom_ui/state-card-text.html
#  extra_html_url_es5:
#    - /local/custom_ui/custom-weather-card.html
#    - /local/custom_ui/state-card-floorplan.html
#    - /local/custom_ui/state-card-tiles_es5.html
#    - /local/custom_ui/state-card-text.html

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
#  api_password: !secret http_password
  base_url: !secret config_base_url
  ssl_key: !secret config_ssl_key
  ssl_certificate: !secret config_ssl_cert

lovelace:
  mode: yaml

mqtt:
  broker: localhost
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

updater:

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# What to put in error logs - comment this out for debugging
logger:
  default: error
  logs:
    homeassistant.components: info
    homeassistant.components.sensor.rest: warning
    homeassistant.components.camera.generic: critical
    homeassistant.helpers.template: critical
    homeassistant.core: error

# View all events in a logbook
logbook:
  include:
    domains:
      - switch
      - automation
      - script
      - device_tracker
      - light
      - persistent_notification
    entities:
      - binary_sensor.octoprint_status_printing
      - binary_sensor.octoprint_status_printing_error
      - sensor.octoprint_current_state 
      - sensor.octoprint_hotend
      - sensor.octoprint_hotend_target
      - sensor.octoprint_bed
      - sensor.octoprint_bed_target
      - sensor.usps_mail
      - sensor.usps_packages
      - sensor.nextcal_message
      - sensor.new_nextcal_location
      - sensor.nextcal_start_time
      - sensor.nextcal_end_time
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping 
      - sensor.rt_acrh13_kbyte_sec_received
      - sensor.rt_acrh13_kbyte_sec_sent
      - sensor.rt_acrh13_bytes_received
      - sensor.rt_acrh13_bytes_sent
      - sensor.myipopendnscom
      - sensor.ha_installed_version
      - sensor.ha_uptime
      - sensor.db_file_system_size
      - sensor.mariadb_database_size
      - sensor.mqtt_topic_home_sysinfo_template_ambient_temperature
      - sensor.mqtt_topic_home_sysinfo_template_serverload
      - sensor.mqtt_topic_home_sysinfo_template_serverspeed
      - sensor.mqtt_topic_home_sysinfo_template_servertemp
      - sensor.battery_gabes_mate
      - sensor.ambient_temp_graph
      - sensor.dark_sky_minutely_summary
      - sensor.btc_exchange_rate
      - sensor.coinbase_bch_wallet
      - sensor.coinbase_eth_wallet
      - sensor.coinbase_ltc_wallet
      - sensor.coinbase_my_vault
      - sensor.coinbase_my_wallet
      - sensor.coinbase_usd_wallet
      - sensor.eth_exchange_rate
      - sensor.ltc_exchange_rate
      - sensor.template_calendar_birthday_date
      - sensor.template_calendar_birthday 
      - sensor.empirestatelights 
      - sensor.mqtt_topic_octo_sysinfo_template_serverload
      - sensor.mqtt_topic_octo_sysinfo_template_serverspeed
      - sensor.mqtt_topic_octo_sysinfo_template_servertemp
      - sensor.mqtt_topic_octo_water_level_template_level
      - sensor.amazonnexthightide
      - sensor.amazonnextlowtide
      - sensor.amazonsunrisetides
      - sensor.amazonsunsettides
      - sensor.mqtt_topic_octo_sysinfo_template_watertemp
      - sensor.monthly_amazon_temp_min
      - sensor.monthly_amazon_temp_lowmed
      - sensor.monthly_amazon_temp_med
      - sensor.monthly_amazon_temp_highmed
      - sensor.monthly_amazon_temp_max
#      - sensor.monthly_amazon_temp
      - sensor.monthly_amazon_ph
      - sensor.reefsysinfo_template_name
      - sensor.reefsysinfo_template_ip
      - sensor.reefsysinfo_template_version
      - sensor.reefsysinfo_template_uptime
      - sensor.onlyreefcontrolcpumemory
      - sensor.onlyreefcontrolpitemp
      - sensor.mqtt_topic_reef_water_level_template_level
      - sensor.reefsunrisetides
      - sensor.reefsunsettides
      - sensor.reefcontrolpilightbrightness
      - sensor.reefcontrolpilightcolor
      - sensor.reefcontrolpipump1status
      - sensor.reefcontrolpipump1statusreverse
      - sensor.reefcontrolpipump2power
      - sensor.noaa_daily_max_reef_temp
      - sensor.reef_high_avg_daily_temp
      - sensor.reef_avg_daily_temp
      - sensor.reef_low_avg_daily_temp
      - sensor.noaa_daily_min_reef_temp
      - input_boolean.reef_temp_daytime_state
      - input_boolean.reef_temp_nightime_state
      - sensor.bali_reef_tides 
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_temperature
      - sensor.mqtt_topic_garden_moisture_level_template_time
      - sensor.mqtt_topic_garden_moisture_level_template_level
      - sensor.mqtt_topic_garden_humidity_template
      - sensor.mqtt_topic_garden_temperature_template
      - sensor.mqtt_topic_garden_humidity_template_time
      - switch.garden_light
      - switch.garden_waterbot
      - sensor.mqtt_topic_garden_water_state_template
      - sensor.mqtt_topic_garden_water_state_time
      - sensor.mqtt_topic_garden_light_state_template
      - sensor.mqtt_topic_garden_light_state_time
      - sensor.tracker_steps
      - sensor.tracker_floors
      - sensor.tracker_distance
      - sensor.tracker_minutes_sedentary
      - sensor.tracker_minutes_lightly_active
      - sensor.tracker_minutes_fairly_active
      - sensor.tracker_minutes_very_active
      - sensor.resting_heart_rate
      - sensor.sleep_efficiency
      - sensor.sleep_start_time
      - sensor.sleep_time_in_bed
      - sensor.sleep_minutes_to_fall_asleep
      - sensor.sleep_minutes_awake
      - sensor.sleep_minutes_asleep
      - binary_sensor.dashboard_motion
      - sensor.mqtt_topic_octoprint_humidity_template
      - sensor.mqtt_topic_octoprint_temperature_template

recorder:
  purge_keep_days: 3
  db_url: !secret config_recorder_url
  include:
    domains:
      - switch
      - automation
      - script
      - device_tracker
      - light
      - persistent_notification
    entities:
      - binary_sensor.octoprint_status_printing
      - binary_sensor.octoprint_status_printing_error
      - sensor.octoprint_current_state 
      - sensor.octoprint_hotend
      - sensor.octoprint_hotend_target
      - sensor.octoprint_bed
      - sensor.octoprint_bed_target
      - sensor.usps_mail
      - sensor.usps_packages
      - sensor.nextcal_message
      - sensor.new_nextcal_location
      - sensor.nextcal_start_time
      - sensor.nextcal_end_time
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping 
      - sensor.rt_acrh13_kbyte_sec_received
      - sensor.rt_acrh13_kbyte_sec_sent
      - sensor.rt_acrh13_bytes_received
      - sensor.rt_acrh13_bytes_sent
      - sensor.myipopendnscom
      - sensor.ha_installed_version
      - sensor.ha_uptime
      - sensor.db_file_system_size
      - sensor.mariadb_database_size
      - sensor.mqtt_topic_home_sysinfo_template_ambient_temperature
      - sensor.mqtt_topic_home_sysinfo_template_serverload
      - sensor.mqtt_topic_home_sysinfo_template_serverspeed
      - sensor.mqtt_topic_home_sysinfo_template_servertemp
      - sensor.battery_gabes_mate
      - sensor.ambient_temp_graph
      - sensor.dark_sky_minutely_summary
      - sensor.btc_exchange_rate
      - sensor.coinbase_bch_wallet
      - sensor.coinbase_eth_wallet
      - sensor.coinbase_ltc_wallet
      - sensor.coinbase_my_vault
      - sensor.coinbase_my_wallet
      - sensor.coinbase_usd_wallet
      - sensor.eth_exchange_rate
      - sensor.ltc_exchange_rate
      - sensor.template_calendar_birthday_date
      - sensor.template_calendar_birthday 
      - sensor.empirestatelights 
      - sensor.mqtt_topic_octo_sysinfo_template_serverload
      - sensor.mqtt_topic_octo_sysinfo_template_serverspeed
      - sensor.mqtt_topic_octo_sysinfo_template_servertemp
      - sensor.mqtt_topic_octo_water_level_template_level
      - sensor.amazonnexthightide
      - sensor.amazonnextlowtide
      - sensor.amazonsunrisetides
      - sensor.amazonsunsettides
      - sensor.mqtt_topic_octo_sysinfo_template_watertemp
      - sensor.filtered_amazon_tank_water_temperature
      - sensor.monthly_amazon_temp_min
      - sensor.monthly_amazon_temp_lowmed
      - sensor.monthly_amazon_temp_med
      - sensor.monthly_amazon_temp_highmed
      - sensor.monthly_amazon_temp_max
#      - sensor.monthly_amazon_temp
      - sensor.monthly_amazon_ph
      - sensor.reefsysinfo_template_name
      - sensor.reefsysinfo_template_ip
      - sensor.reefsysinfo_template_version
      - sensor.reefsysinfo_template_uptime
      - sensor.onlyreefcontrolcpumemory
      - sensor.onlyreefcontrolpitemp
      - sensor.mqtt_topic_reef_water_level_template_level
      - sensor.reefsunrisetides
      - sensor.reefsunsettides
      - sensor.reefcontrolpilightbrightness
      - sensor.reefcontrolpilightcolor
      - sensor.reefcontrolpipump1status
      - sensor.reefcontrolpipump1statusreverse
      - sensor.reefcontrolpipump2power
      - sensor.noaa_daily_max_reef_temp
      - sensor.reef_high_avg_daily_temp
      - sensor.reef_avg_daily_temp
      - sensor.reef_low_avg_daily_temp
      - sensor.noaa_daily_min_reef_temp
      - input_boolean.reef_temp_daytime_state
      - input_boolean.reef_temp_nightime_state
      - sensor.bali_reef_tides
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_temperature
      - sensor.mqtt_topic_garden_moisture_level_template_time
      - sensor.mqtt_topic_garden_moisture_level_template_level
      - sensor.mqtt_topic_garden_humidity_template
      - sensor.mqtt_topic_garden_temperature_template
      - sensor.mqtt_topic_garden_humidity_template_time
      - sensor.filtered_garden_temperature
      - sensor.filtered_garden_humidity
      - switch.garden_light
      - switch.garden_waterbot
      - sensor.mqtt_topic_garden_water_state_template
      - sensor.mqtt_topic_garden_water_state_time
      - sensor.mqtt_topic_garden_light_state_template
      - sensor.mqtt_topic_garden_light_state_time
      - sensor.tracker_steps
      - sensor.tracker_floors
      - sensor.tracker_distance
      - sensor.tracker_minutes_sedentary
      - sensor.tracker_minutes_lightly_active
      - sensor.tracker_minutes_fairly_active
      - sensor.tracker_minutes_very_active
      - sensor.resting_heart_rate
      - sensor.sleep_efficiency
      - sensor.sleep_start_time
      - sensor.sleep_time_in_bed
      - sensor.sleep_minutes_to_fall_asleep
      - sensor.sleep_minutes_awake
      - sensor.sleep_minutes_asleep
      - binary_sensor.dashboard_motion
      - sensor.mqtt_topic_octoprint_humidity_template
      - sensor.mqtt_topic_octoprint_temperature_template

#Panels
#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml

weather: 
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Pandora through Pianobar
media_player 2:
  - platform: pandora

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#Alexa
alexa:

#IFTTT
ifttt:
  key: !secret ifttt_key

#NRF Sensor
mysensors:
  gateways:
    - device: '192.168.50.111'

#Pilight 433mhz receiver
pilight:
  host: 192.168.50.111
  port: 5000

#Tuya Smart Switches
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1

#OctoPrint 3D Printer
octoprint:
  host: octopi.local
  api_key: !secret octoprint_apikey
  bed: true
  number_of_tools: 2

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

#Foursquare
foursquare:
  access_token: !secret foursquare_access_token
  push_secret: !secret foursquare_pushsecret

coinbase:
  api_key: !secret coinbase_api_key
  api_secret: !secret coinbase_api_secret
  exchange_rate_currencies:
    - BTC
    - ETH
    - LTC

notify:
  - name: octo_cam_bot_notifier
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret

notify 2:
  - platform: command_line
    name: gabes_alexa
    command: /home/homeassistant/.homeassistant/scripts/alexa_wrapper.sh -d "Gabe's Alexa"

notify 3:
  - name: kiosk
    platform: command_line
    command: "/home/homeassistant/.homeassistant/tts/kiosk_tts.py"

# lovelace theme notification
input_text:
  notification_text:
    name: Notification Text
    pattern: '[a-fA-F0-9]*'
    initial: No Message

python_script:

hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: true

# alexa integration
emulated_hue:
  host_ip: 192.168.50.111
  exposed_domains:
  - switch
  - scene
  - script
  entities:
    switch.06200940dc4f22cbb94b_4:
      name: "Reef Light"
    switch.harmony_watch_roku:
      name: "Tee Vee" 
    switch.kessil_light_level_11:
      name: "Reef Blue Lights" 
    switch.kessil_light_level_5:
      name: "Reef Bright Lights"
    switch.2437254184f3eb695327:
      name: "Printer"
    switch.octofishfeeder:
      name: "Fish Feeder"
    switch.2437254184f3eb695715:
      name: "Home Assistant"
    switch.06200940dc4f22cbb94b_7:
      name: "Reef Pie"
    switch.reef_pump_1:
      name: "Reef Top Up" 
    switch.reef_pump_1_reverse:
      name: "Reef Reverse Pump" 
    switch.reef_pump_2:
      name: "Reef Doser" 
    switch.2437254184f3eb695276:
      name: "Reef Sump" 
    light.table:
      name: "Table Light" 

asuswrt:
  host: !secret asuswrt_host
  username: !secret asuswrt_username
#  password: !secret asuswrt_password
  protocol: ssh
  port: 22
  ssh_key: !secret asuswrt_ssh_key
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

downloader:
  download_dir: www/images/

shopping_list:

system_health:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# This crashes the pi
#image_processing:
#  - platform: tensorflow
#    source:
#      - entity_id: camera.housecam
#    model:
#      graph: /home/homeassistant/.homeassistant/tensorflow/frozen_inference_graph.pb

#feedreader:
#  urls:
#    - https://twitrss.me/twitter_user_to_rss/?user=octo_cam_bot
#    - https://twitrss.me/twitter_user_to_rss/?user=sfgabe
#  scan_interval:
#    minutes: 20
#  max_entries: 1

scene: !include scenes.yaml
zone: !include zone.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
history_graph: !include history_graph.yaml
climate: !include climate.yaml
rest_command: !include rest_command.yaml
device_tracker: !include device_tracker.yaml
switch: !include switches.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
intent_script: !include intent_script.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
