homeassistant:
  name: !secret config_name
  latitude: !secret config_lat
  longitude: !secret config_long
  elevation: !secret config_elev
  unit_system: imperial
  time_zone: !secret config_tz
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
      - /home/homeassistant/.homeassistant/scripts
      - /home/homeassistant/.homeassistant/www/images/
      - /home/homeassistant/.homeassistant/downloads/

# Enables the frontend
frontend: 
  javascript_version: latest
  themes: !include configuration_themes.yaml

# Enables configuration UI
config:

api:

http:
  api_password: !secret http_password
  base_url: !secret config_base_url
  ssl_key: !secret config_ssl_key
  ssl_certificate: !secret config_ssl_cert

lovelace:
  mode: yaml

mqtt:
  broker: localhost
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

updater:

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# What to put in error logs - comment this out for debugging
logger:
  default: error
  logs:
    homeassistant.components: info
    homeassistant.components.sensor.rest: warning
    homeassistant.components.camera.generic: critical
    homeassistant.helpers.template: critical
    homeassistant.core: error
    homeassistant.components.websocket_api: debug

weather: 
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'en'

# Cloud
cloud:

#Alexa
alexa:

#IFTTT
ifttt:
  key: !secret ifttt_key

#NRF Sensor
mysensors:
  gateways:
    - device: '192.168.50.111'

#Pilight 433mhz receiver
pilight:
  host: 192.168.50.111
  port: 5000

#Tuya Smart Switches
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1

#OctoPrint 3D Printer
octoprint:
  host: octopi.local
  api_key: !secret octoprint_apikey
  bed: true
  number_of_tools: 2

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

#Foursquare
foursquare:
  access_token: !secret foursquare_access_token
  push_secret: !secret foursquare_pushsecret

coinbase:
  api_key: !secret coinbase_api_key
  api_secret: !secret coinbase_api_secret
  exchange_rate_currencies:
    - BTC
    - ETH
    - LTC

# lovelace theme notification
input_text:
  notification_text:
    name: Notification Text
    pattern: '[a-fA-F0-9]*'
    initial: No Message

python_script:

hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: true

# alexa integration
emulated_hue: !include emulated_hue.yaml

asuswrt:
  host: !secret asuswrt_host
  username: !secret asuswrt_username
#  password: !secret asuswrt_password
  protocol: ssh
  port: 22
  ssh_key: !secret asuswrt_ssh_key
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

downloader:
  download_dir: www/images/

shopping_list:

system_health:

## cpu speed raspberry device
- platform: cpuspeed

## system monitor raspberry device
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: disk_use_percent
    arg: /var/log
  - type: memory_use_percent
  - type: memory_use
  - type: memory_free
  - type: processor_use
  - type: swap_use_percent
  - type: swap_use
  - type: swap_free
  - type: last_boot
  - type: since_last_boot
## LAN Adapter
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: packets_in
    arg: eth0
  - type: packets_out
    arg: eth0
  - type: ipv4_address
    arg: eth0
  - type: ipv6_address
    arg: eth0
## WLAN Adapter   
  - type: network_in
    arg: wlan0
  - type: network_out
    arg: wlan0
  - type: packets_in
    arg: wlan0
  - type: packets_out
    arg: wlan0
  - type: ipv4_address
    arg: wlan0
  - type: ipv6_address
    arg: wlan0

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

#esphome:
#  name: bedroom
#  platform: ESP8266
#  board: nodemcuv2

person:
  - name: Gabe
    id: gabe
    user_id: 152003d68d7646c396665d9da58122d5
    device_trackers:
      - device_tracker.5re0217120001465_2
      - device_tracker.gabesmatehotspot
      - device_tracker.google_maps_114555423860561989456
      - device_tracker.hassio_gabesmatephone
      - device_tracker.huawei_mate_9_92528f2b1a5
#  old    - device_tracker.huawei_mate_992528f2b1a5
#  tablet?    - device_tracker.android_c42e1d9b846bb1c6
      - device_tracker.phone
  - name: Berny
    id: berny
    device_trackers:
      - device_tracker.bernys_iphone

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  scan_interval: 60
  grace_period: 600
#  debug: true

#gpodder:
#  username: !secret gpodder_udername
#  password: !secret gpodder_password
#  sensor:
#    - enabled: true
#      name: homeassistant
#      device: kiosk

# This crashes the pi
#image_processing:
#  - platform: tensorflow
#    source:
#      - entity_id: camera.housecam
#    model:
#      graph: /home/homeassistant/.homeassistant/tensorflow/frozen_inference_graph.pb

#feedreader:
#  urls:
#    - https://twitrss.me/twitter_user_to_rss/?user=octo_cam_bot
#    - https://twitrss.me/twitter_user_to_rss/?user=sfgabe
#  scan_interval:
#    minutes: 20
#  max_entries: 1

media_player: !include media_player.yaml
notify: !include notify.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
plant: !include plants.yaml
scene: !include scenes.yaml
zone: !include zone.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
history_graph: !include history_graph.yaml
climate: !include climate.yaml
rest_command: !include rest_command.yaml
device_tracker: !include device_tracker.yaml
switch: !include switches.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
intent_script: !include intent_script.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml

